.PHONY: clean All

All:
	@echo "----------Building project:[ version3 - Debug ]----------"
	@cd "version3" && "$(MAKE)" -f  "version3.mk"
clean:
	@echo "----------Cleaning project:[ version3 - Debug ]----------"
	@cd "version3" && "$(MAKE)" -f  "version3.mk" clean
